name: segmentation

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - opencv
  - tqdm
  - matplotlib
  - imageio
  - pip:
    - torch
    - torchvision
    - scikit-learn
    - scikit-image
    - pandas
